"""Add vision metadata to images

Revision ID: 2687d47a7a40
Revises: 778833e818e7
Create Date: 2026-10-01 15:40:41.362434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2687d47a7a40'
down_revision: Union[str, Sequence[str], None] = '778833e818e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('images', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'confidence')
    op.drop_column('images', 'tags')
    # ### end Alembic commands ###
